In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from xgboost import XGBClassifier
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import KFold,cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score

In [38]:
train = np.array(np.genfromtxt ('adult.data',delimiter = ',' ,dtype = np.str), dtype = np.object)
test = np.array(np.genfromtxt ('adult.test',delimiter = ',', dtype = np.str), dtype = np.object)


In [39]:
train[:,[0,2,4,10,11,12]] = train[:,[0,2,4,10,11,12]].astype(np.float)

In [40]:
enc1 = OrdinalEncoder()
enc1.fit(train[:,[1,3,5,6,7,8,9,13,14]])
train[:,[1,3,5,6,7,8,9,13,14]] = enc1.transform(train[:,[1,3,5,6,7,8,9,13,14]])
test[:,[1,3,5,6,7,8,9,13,14]] = enc1.transform(test[:,[1,3,5,6,7,8,9,13,14]])

In [41]:
train[:3,[1,3,5,6,7,8,9,13,14]]

array([[7.0, 9.0, 4.0, 1.0, 1.0, 4.0, 1.0, 39.0, 0.0],
       [6.0, 9.0, 2.0, 4.0, 0.0, 4.0, 1.0, 39.0, 0.0],
       [4.0, 11.0, 0.0, 6.0, 1.0, 4.0, 1.0, 39.0, 0.0]], dtype=object)

In [42]:
train = train.astype(np.float)
test = test.astype(np.float)

In [43]:
Xtrain = train[:,:-1]
ytrain = train[:,-1]
Xtest = test[:,:-1]
ytest = test[:,-1]

In [44]:
m1 = XGBClassifier(use_label_encoder =False)
m1.fit(Xtrain,ytrain)
ypred = m1.predict(Xtest)

acc = accuracy_score(ytest,ypred)

C:\Users\SAGAR\AppData\Roaming\Python\Python37\site-packages\xgboost\data.py:106: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


In [45]:
print (" Accuracy on test : ", acc)
print ("Confusion Matrix of test : \n ", confusion_matrix(ytest,ypred))

 Accuracy on test :  0.8700939745715865
Confusion Matrix of test : 
  [[11643   792]
 [ 1323  2523]]


In [46]:
ypred_train = m1.predict(Xtrain)
print (" Accuracy on train : ",accuracy_score(ytrain,ypred_train))
print ("Confusion Matrix of train :\n ", confusion_matrix(ytrain,ypred_train))

 Accuracy on train :  0.9043334049937041
Confusion Matrix of train :
  [[23667  1053]
 [ 2062  5779]]


In [47]:
m2 = XGBClassifier(use_label_encoder =False)
m2.fit(Xtrain1,ytrain1)
ypred2 = m2.predict(Xtest1)

acc2 = accuracy_score(ytest1,ypred2)
acc2

0.8700939745715865

In [48]:
print (confusion_matrix(ytrain,ypred_train))
print (confusion_matrix(ytest,ypred))
print (confusion_matrix(ytest1,ypred2))

[[23667  1053]
 [ 2062  5779]]
[[11643   792]
 [ 1323  2523]]
[[11643   792]
 [ 1323  2523]]


In [49]:

#result = cross_val_score(m1,Xtrain,ytrain,cv = kfold)

#result

In [50]:
m = [0.3,0.2,0.1,0.01,0.001]
kf = KFold(n_splits=10, random_state=7, shuffle = False)
acc_hp = []
for i in m:
    m4 = XGBClassifier(verbosity = 0, use_label_encoder =False, eta = i)
    acc_kfold = []
    for train_index, test_index in kf.split(Xtrain):
        X_train2, X_val2 = Xtrain[train_index], Xtrain[test_index]
        y_train2, y_val2 = ytrain[train_index], ytrain[test_index]
        m4.fit(X_train2,y_train2)
        ypred11 = m4.predict(X_val2)
        acc_kfold.append(accuracy_score(y_val2,ypred11))
    acc_hp.append(np.max(acc_kfold))

print (acc_hp)

[0.8808353808353808, 0.8826781326781327, 0.8808353808353808, 0.8639434889434889, 0.8627149877149877]


In [51]:
for i in range (5) :
    print ("learning rate and accuracy : ", (m[i],acc_hp[i]))

learning rate and accuracy :  (0.3, 0.8808353808353808)
learning rate and accuracy :  (0.2, 0.8826781326781327)
learning rate and accuracy :  (0.1, 0.8808353808353808)
learning rate and accuracy :  (0.01, 0.8639434889434889)
learning rate and accuracy :  (0.001, 0.8627149877149877)


In [52]:
mf = XGBClassifier(use_label_encoder =False, eta = 0.2 )
mf.fit(Xtrain,ytrain)
ypred2 = mf.predict(Xtest)

acc2 = accuracy_score(ytest,ypred2)
acc2

0.8727965112708065

In [53]:
print (confusion_matrix(ytest,ypred2))

[[11679   756]
 [ 1315  2531]]


In [54]:
m = [0.3,0.2,0.1,0.01,0.001]
kf = KFold(n_splits=10, random_state=7, shuffle = False)
acc_hp = []
for i in m:
    m4 = XGBClassifier(verbosity = 0, use_label_encoder =False, learning_rate = i)
    acc_kfold = []
    for train_index, test_index in kf.split(Xtrain):
        X_train2, X_val2 = Xtrain[train_index], Xtrain[test_index]
        y_train2, y_val2 = ytrain[train_index], ytrain[test_index]
        m4.fit(X_train2,y_train2)
        ypred11 = m4.predict(X_val2)
        acc_kfold.append(accuracy_score(y_val2,ypred11))
    acc_hp.append(np.mean(acc_kfold))

print (acc_hp)

[0.8699672751714507, 0.873744831581798, 0.8728543096366247, 0.8553794077243572, 0.8536289632083307]


In [55]:
for i in range (5) :
    print ("learning rate and accuracy : ", (m[i],acc_hp[i]))

mf = XGBClassifier(use_label_encoder =False, eta = 0.2 )
mf.fit(Xtrain,ytrain)
ypred2 = mf.predict(Xtest)

acc2 = accuracy_score(ytest,ypred2)
print ("Accuracy Score", acc2)

print (confusion_matrix(ytest,ypred2))

learning rate and accuracy :  (0.3, 0.8699672751714507)
learning rate and accuracy :  (0.2, 0.873744831581798)
learning rate and accuracy :  (0.1, 0.8728543096366247)
learning rate and accuracy :  (0.01, 0.8553794077243572)
learning rate and accuracy :  (0.001, 0.8536289632083307)
Accuracy Score 0.8727965112708065
[[11679   756]
 [ 1315  2531]]
